### ISSUE TITLE
Offline Carrier Jump not sent to EDSM

### ISSUE THREAD

**Issue by artig4n** [EDCD/EDMarketConnector#713]
CMDR Codger here. 

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5261506/EDMarketConnector.log)

As requested on the ED forums, here's the log from yesterday.

**Comment by Athanasius** [comment]
For our reference, forum post: https://forums.frontier.co.uk/threads/elite-dangerous-market-connector-edmc.548869/post-8712280

**Comment by artig4n** [comment]
Here's a new log from just now, with a pic showing that EDSM does not have the right location yet. 

All I did was carrier jump while offline, then run ED, then run EDMC. 

![EDSM example](https://user-images.githubusercontent.com/71708959/93888760-47081b00-fc9d-11ea-8e27-47a734fc7c32.JPG)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5261712/EDMarketConnector.log)

**Comment by Athanasius** [comment]
Let me get beta6 out, which will have some additional logging.  This will allow us to see if EDMC is even attempting to send the required event(s) to EDSM, and if so what form they take.

**Comment by Athanasius** [comment]
Please try with https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.0-beta6 and if it still fails then attach a fresh copy of the debug log file to this issue.

**Comment by artig4n** [comment]
Ok, I ran the new EDMC, and set logging to Debug. Then I exited everything, and let the carrier jump. Logged back into ED, ran EDMC. 

EDSM was still not updated. Here's the log.

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5262725/EDMarketConnector.log)

**Comment by Athanasius** [comment]
Well, that's weird, because apparently the EDSM pluging didn't even see a Location or Docked event, and it should when you login to the game.

Can you attach the Journal file from that login please ?  Also, if you can re-run the test and also attach the non-folder EDMarketConnector.log as that contains a little bit of extra output that the debug file doesn't capture (but gets overwritten each time you re-run EDMC).

**Comment by artig4n** [comment]
I don't know what you mean by the non-folder log. 

Here's the journal, though. 
[Journal.200922091050.01.log](https://github.com/EDCD/EDMarketConnector/files/5262859/Journal.200922091050.01.log)

Let me go back to the carrier, and I'll re-run the test. It'll just take a few minutes.

**Comment by Athanasius** [comment]
`%TEMP%\EDMarketConnector.log` - it's the older logfile that captures *all* console output from the program, and will have things like exception traces in it.

**Comment by Athanasius** [comment]
Can you confirm you're in a time zone that's 7 hours behind game time ?   Probably US Pacific Time ?

**Comment by artig4n** [comment]
Yes, US West Coast.

**Comment by artig4n** [comment]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5262965/EDMarketConnector.log)

**Comment by artig4n** [comment]
Ok, I re-ran the test, with the same results. Here are the various logs and journals.

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5263009/EDMarketConnector.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5263012/EDMarketConnector.log)
[Journal.200922101416.01.log](https://github.com/EDCD/EDMarketConnector/files/5263013/Journal.200922101416.01.log)

**Comment by Athanasius** [comment]
Sadly no exception in there to point a finger.  I'll have a play tomorrow with using those Journal files, in edited form, to play into my own EDMC and see what happens.

**Comment by artig4n** [comment]
Let me know if there's anything else you need from me. :)

**Comment by Athanasius** [comment]
> Let me know if there's anything else you need from me. :)

Probably not today, but I'm going to add some more logging to other parts so expect a beta7 some time tomorrow.

**Comment by Athanasius** [comment]
Please run [4.1.0-beta7](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.0-beta7) and upload Journal and log files.

**Comment by artig4n** [comment]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5268115/EDMarketConnector.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5268116/EDMarketConnector.log)
[Journal.200923053237.01.log](https://github.com/EDCD/EDMarketConnector/files/5268120/Journal.200923053237.01.log)

**Comment by Athanasius** [comment]
Are you running EDMC *after* you login to the game?  That's the only way I can get those files to make sense.

Replaying your log file my end (up to just before you load into the game with EDMC running, and then appending the rest after) has it work perfectly.

**Comment by artig4n** [comment]
Yes. My usual procedure is to run the game first, then EDMC. This is because I've on occasion had EDMC throw an error if I run it before the game has started. I didn't think it made any difference. I can do it the other way around if that helps.

**Comment by Athanasius** [comment]
> Yes. My usual procedure is to run the game first, then EDMC. This is because I've on occasion had EDMC throw an error if I run it before the game has started. I didn't think it made any difference. I can do it the other way around if that helps.

That is *exactly* what's causing the problem.  When EDMC starts up it doesn't fully process 'old' lines from the Journal, it just reads through them to get to the end of the file.  Thus it will NOT process the 'Location' event and not even think about throwing it at the EDSM plugin.

So, yes, always start EDMC first if you want everything in the game session to be processed.  Open a new ticket for any issue you run into doing that.

**Comment by Athanasius** [comment]
Thinking about this some more, it's obviously not desirable to just blindly process the latest journal file fully at startup because what if the user simply restarted EDMC?  We'd end up re-sending everything.

There's room for perhaps acting on a small subset of events, like Location, though.

**Comment by artig4n** [comment]
All right, I'll start EDMC first, then. If I remember, lol. 

I guess I had this illusion that it could tell somehow what it had already processed, and would take it up from there. Thinking about it more, I realize that it would require some sort of stateful storage, so... yeah. Don't know why I thought that.

Thanks for the help!

**Comment by artig4n** [comment]
Ok, I'm like 98% sure that it really IS missing the updates sometimes, even when EDMC is running when the game is launched.

I've tested this multiple times before bugging you about it again. 

Here's what's happening. If I log out of ED and EDMC after scheduling a jump, wait until the jump is complete, and then log back into EDMC first, then ED, then I find that EDSM is not updated with my location.

If I think exit to Main menu and log back into ED, leaving EDMC running, then it updates correctly.

Here's the logs and journals from just now when it happened.  

[Journal.200928060829.01.log](https://github.com/EDCD/EDMarketConnector/files/5292479/Journal.200928060829.01.log)

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5292460/EDMarketConnector.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5292463/EDMarketConnector.log)

**Comment by Athanasius** [comment]
We're starting to suspect there's an issue with your system clock:

1. startup is at `2020-09-28 06:07:01.701 - INFO - EDMarketConnector.__main__:1064: Startup v4.1.0-beta7 : Running on Python v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]`
1. That initially loads the previous day's journal as expected. and finds past Location events, not acting on them.
1. Then it finds the journal you supplied:
`2020-09-28 06:08:29.862 - INFO - monitor.EDLogs.worker:313: New Journal File. Was "C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous\Journal.200925175426.01.log", now "C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous\Journal.200928060829.01.log"`
1. But then we log:
`2020-09-28 06:09:13.332 - DEBUG - monitor.EDLogs.worker:330: Found "Location" event, appending to event_queue`
when the actual Location event is:
`{ "timestamp":"2020-09-28T13:09:47Z", "event":"Location", `

And that means we saw the event ~34 seconds *before* it happened.

Now, whilst this points to your system clock being slow (assuming the journal timestamps are from a game server time source, and that's correct), and that shouldn't be causing EDSM to reject the message, we'd still like you to check your system clock is actually properly sync'd and then retry this.  There's a "sync now" button on "Date and time settings" on Windows 10 Settings.

Meanwhile I'll continue looking more closely at these log files....

**Comment by Athanasius** [comment]
We do go on to log:
```py
2020-09-28 06:09:13.447 - DEBUG - plugins.edsm.worker:533: pending has at least one of ('CarrierJump', 'FSDJump', 'Location', 'Docked') and it passed should_send()
2020-09-28 06:09:13.447 - DEBUG - plugins.edsm.worker:538: "Location" event in pending passed should_send(), timestamp: 2020-09-28T13:09:47Z
2020-09-28 06:09:13.450 - DEBUG - plugins.edsm.worker:557: pending has at least one of ('CarrierJump', 'FSDJump', 'Location', 'Docked') Attempting API cal...```

So we do attempt an EDSM API call with that event included.  It's then up to EDSM what it does with it.  There are two subsequent warnings back from EDSM about it not knowing about AutoScan events.  Those might not be from the same API call though (we're only logging the four events: Docked, Location, CarrierJump and FSDJump, and only Location in detail).  If they *are* from the same API call then this looks like an EDSM bug.

**Comment by Athanasius** [comment]
We have another theory, that we're checking with Anthor, that perhaps EDSM doesn't react well to a *Location* event in this manner.  Maybe it plain doesn't want to move an FC from it.  Maybe it's an ordering thing.  Maybe it moves the FC, but then not you.

**Comment by artig4n** [comment]
Ok, I checked my system clock, and it was set to automatically sync. But it also said the last sync was a month ago, so I hit the manual sync button. That did move the time ahead a bit. So that might be part of the problem.

**Comment by artig4n** [comment]
Ok, I tested again after sync'ing the clock, but there was no difference.

**Comment by Athanasius** [comment]
Anthor has been checking the code his end, and this should work.  He's going to add some extra code his end to aid in debugging and will presumably be in touch to get you to re-test so he knows timestamps.

One thing to note, if you use a *later* beta of EDMC you'll need to run it with TRACE debugging enabled in order to have this stuff properly logged.  So use a CMD.EXE window, `cd` to the install location (default `c:\Program Files (x86)\EDMarketConnector\`) and then run `EDMarketConnector.exe --trace`.

**Comment by artig4n** [comment]
Ok, I'll be glad to test some more when he's ready.

**Comment by Athanasius** [comment]
You probably just want to run 4.1.0-rc1 via the TRACE bat file and then let us know you tested anew.  Then @AnthorNet can check any logging he's added his end.

**Comment by artig4n** [comment]
Ok, here's the logs. But things are really messed up now. It shows me as being in Dvorsi, a place I've never been (as far as I recall) and which is 22,000LY or so from my actual current position. Even after logging off to Main Menu and back on, it's still showing Dvorsi.

I tried a manual update also, no change.

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5300464/EDMarketConnector.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5300468/EDMarketConnector.log)
[Journal.200929091550.01.log](https://github.com/EDCD/EDMarketConnector/files/5300472/Journal.200929091550.01.log)
![EDSM example 2](https://user-images.githubusercontent.com/71708959/94585965-8a323300-0235-11eb-92d0-13e9191121bd.JPG)

**Comment by AnthorNet** [comment]
This is happening because the Fleet Carrier is still mentioned as being in that system. Need to fix that.

**Comment by AnthorNet** [comment]
Should be fixed now.

**Comment by Athanasius** [comment]
I'll close this once @artig4n has confirmed it's now working for them.

**Comment by artig4n** [comment]
Still broken. Here's the logs.

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5305327/EDMarketConnector.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5305332/EDMarketConnector.log)
[Journal.200930051026.01.log](https://github.com/EDCD/EDMarketConnector/files/5305336/Journal.200930051026.01.log)

![EDSM example 3](https://user-images.githubusercontent.com/71708959/94683879-1139e680-02dc-11eb-9d3b-89b0b9ad45a6.JPG)

**Comment by AnthorNet** [comment]
Just imported your journal from your account and it works, so now it's not on my side :p At least ;)

**Comment by artig4n** [comment]
It always worked when I imported the journal, I think. That's how I was fixing my flight log on this trip. Perhaps the new logs will show where it's getting lost.

**Comment by Athanasius** [comment]
> Just imported your journal from your account and it works, so now it's not on my side :p At least ;)

But a Journal import obviously has *all* of the journal available, versus EDMC only sending some bits.  So what extra bits would be needed if this is indeed a bug our side, given that normal FSDJump obviously works ?

**Comment by AnthorNet** [comment]
I'm downloading the access log to check, but normally the Location event should have all it needs on its own to work.

**Comment by Athanasius** [comment]
> Still broken. Here's the logs.
> 
> [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5305327/EDMarketConnector.log)
> [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5305332/EDMarketConnector.log)
> [Journal.200930051026.01.log](https://github.com/EDCD/EDMarketConnector/files/5305336/Journal.200930051026.01.log)
> 
> ![EDSM example 3](https://user-images.githubusercontent.com/71708959/94683879-1139e680-02dc-11eb-9d3b-89b0b9ad45a6.JPG)

At:

`2020-09-30 05:13:00.497 - TRACE - plugins.edsm.worker:564: Event: ...`

We're sending:

```py
{'timestamp': '2020-09-30T12:13:00Z', 'event': 'Location', 'Docked': True, 'StationName': 'Q7K-02N', 'StationType': 'FleetCarrier', 'MarketID': 3700446720, 'StationFaction': OrderedDict([('Name', 'FleetCarrier')]), 'StationGovernment': '$government_Carrier;', 'StationGovernment_Localised': 'Private Ownership ', 'StationServices': ['dock', 'autodock', 'commodities', 'contacts', 'crewlounge', 'engineer', 'flightcontroller', 'stationoperations', 'stationMenu', 'carriermanagement', 'carrierfuel'], 'StationEconomy': '$economy_Carrier;', 'StationEconomy_Localised': 'Private Enterprise', 'StationEconomies': [OrderedDict([('Name', '$economy_Carrier;'), ('Name_Localised', 'Private Enterprise'), ('Proportion', 1.0)])], 'StarSystem': 'Zuni LC-U d3-837', 'SystemAddress': 28769695928995, 'StarPos': [523.5625, 523.625, 23623.59375], 'SystemAllegiance': '', 'SystemEconomy': '$economy_None;', 'SystemEconomy_Localised': 'None', 'SystemSecondEconomy': '$economy_None;', 'SystemSecondEconomy_Localised': 'None', 'SystemGovernment': '$government_None;', 'SystemGovernment_Localised': 'None', 'SystemSecurity': '$GAlAXY_MAP_INFO_state_anarchy;', 'SystemSecurity_Localised': 'Anarchy', 'Population': 0, 'Body': 'Zuni LC-U d3-837 A', 'BodyID': 1, 'BodyType': 'Star', '_systemName': 'Zuni LC-U d3-837', '_systemCoordinates': [523.5625, 523.625, 23623.59375], '_stationName': 'Q7K-02N', '_shipId': None}```

I don't see how this can be an issue our end.

**Comment by Athanasius** [comment]
@AnthorNet If you look at the second EDMarketConnector.log file (the one that includes a line `E:D Market Connector 4.1.0-rc1` after the Locale lines), you'll see a sequence of:

`2020-09-30 05:13:00.490 - TRACE - plugins.edsm.worker:558: pending has at least one of ('CarrierJump', 'FSDJump', 'Location', 'Docked') Attempting API call with the following events:`

followed by a series of lines:

`2020-09-30 05:13:00.491 - TRACE - plugins.edsm.worker:564: Event: ...`
Which are the python objects we're about to serialise into the EDSM API call, and then send.  Is there any clue with it being that specific set of events, in that specific order ?

**Comment by Athanasius** [comment]
@artig4n Please re-try with the new https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.0-rc2

**NB: You should be attaching `EDMarketConnector-debug.log` from the sub-folder now.  The name changed, it's why you attached an old/wrong one in the comment above!**  And remember to run it with the TRACE bat file.

@AnthorNet This one will log any non-1XX specific event code, so we'll know if something your end is rejecting the event at all.

**Comment by artig4n** [comment]
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5311843/EDMarketConnector-debug.log)
[Journal.201001051629.01.log](https://github.com/EDCD/EDMarketConnector/files/5311848/Journal.201001051629.01.log)

**Comment by AnthorNet** [comment]
I've put some sentry on the Location event, I'll get to you if I receive anything.
Right now, EDMC never triggers the code to update the stations system.

**Comment by Athanasius** [comment]
@AnthorNet in that last debug log there's 10 events sent, including the Location, and the response has 10 msgnum == 100 in it.  So your end at least thinks it's seen all the events and not found an error in them.

**Comment by AnthorNet** [comment]
Yes the Sentry I put in place correctly receive all the events, and parse Location event.
All seems to be correct, so I'm not sure why it doesn't update.

**Comment by artig4n** [comment]
You want me to test again, I guess?

**Comment by artig4n** [comment]
Here's another test. EDSM was not updated with my location, as before.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5312566/EDMarketConnector-debug.log)
[Journal.201001070304.01.log](https://github.com/EDCD/EDMarketConnector/files/5312571/Journal.201001070304.01.log)

**Comment by AnthorNet** [comment]
I did receive the.locatiin event but I'll have to add.more debug on my side. That's very odd. Other edmc instances were working correctly as EDD and the journal import from.edsm.

**Comment by artig4n** [comment]
I've been wondering if it's related to jumping into an undiscovered system, because that's all I've been doing. It's all first discoveries around here at the moment. Just a thought, I don't know what's in the code at all :)

**Comment by AnthorNet** [comment]
Make sense, I'll go that way tomorrow!

**Comment by artig4n** [comment]
I have noticed that if I exit the game, leaving EDMC running, and then enter the game again (without doing anything else), then EDSM will get updated with my location. Maybe that's a clue.

**Comment by artig4n** [comment]
Funny sidenote, I signed up for EDSM way back when on my original account (Artigan Lamarr), which is now my alt. I mostly use the Codger account now. Today, I just got an email from EDSM.net saying that my Artigan Lamarr account has been deleted due to inactivity. :)

**Comment by artig4n** [comment]
This appears to be fixed. The last few jumps everything has updated correctly :)

**Comment by AnthorNet** [comment]
I'm very glad to hear it :) Systems creation on lookup was the missing part it seems!
